//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theater.ApplicationData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TheaterEntities10 : DbContext
    {
        public TheaterEntities10()
            : base("name=TheaterEntities10")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<actors> actors { get; set; }
        public virtual DbSet<actors_role> actors_role { get; set; }
        public virtual DbSet<basket> basket { get; set; }
        public virtual DbSet<inventory> inventory { get; set; }
        public virtual DbSet<inventory_item_name> inventory_item_name { get; set; }
        public virtual DbSet<performance> performance { get; set; }
        public virtual DbSet<photo> photo { get; set; }
        public virtual DbSet<review> review { get; set; }
        public virtual DbSet<role> role { get; set; }
        public virtual DbSet<showtime> showtime { get; set; }
        public virtual DbSet<sponsor> sponsor { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<theater> theater { get; set; }
        public virtual DbSet<tickets> tickets { get; set; }
        public virtual DbSet<user_role> user_role { get; set; }
        public virtual DbSet<users> users { get; set; }
        public virtual DbSet<viewer> viewer { get; set; }
    }
}
