//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theater.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class performance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public performance()
        {
            this.role = new HashSet<role>();
            this.showtime = new HashSet<showtime>();
        }
    
        public int id_performans { get; set; }
        public string title { get; set; }
        public string genre { get; set; }
        public int year_created { get; set; }
        public string author { get; set; }
        public System.TimeSpan duration { get; set; }
        public int id_photo { get; set; }
    
        public virtual photo photo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<role> role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<showtime> showtime { get; set; }

        public string PerformancePhotoPath
        {

            get
            {
                return MethodsForDB.PhotoPath(photo.photo1);
            }
        }
    }
}
