//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theater.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public int id_review { get; set; }
        public string critic_name { get; set; }
        public string review1 { get; set; }
        public double rating { get; set; }
        public int id_showtime { get; set; }
    
        public virtual showtime showtime { get; set; }
    }
}
