//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theater.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class sponsor
    {
        public int id_sponsor { get; set; }
        public string company_name { get; set; }
        public string contact_info { get; set; }
        public int id_photo { get; set; }
    
        public virtual photo photo { get; set; }

        public string SponsorPhotoPath
        {

            get
            {
                return MethodsForDB.PhotoPath(photo.id_photo);
            }
        }
    }
}
