//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace theater.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tickets
    {
        public int id_ticket { get; set; }
        public int id_showtime { get; set; }
        public int seat_row { get; set; }
        public int seat_number { get; set; }
        public double price { get; set; }
        public System.DateTime date_sold { get; set; }
        public int id_viewer { get; set; }
        public int id_theater_building { get; set; }
    
        public virtual showtime showtime { get; set; }
        public virtual theater theater { get; set; }
        public virtual viewer viewer { get; set; }
    }
}
